export const Learningpacks = [
  {
    id: 0,
    name: "0-12 months",
    description: "Engage both sides of the brain and discover.",
    delivery: "Delivers | every 2 months",
    pricing: "$80/Pack",
    gridItems: 3,
    scrollId: "0_12_months",
    items: [
      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072560/Songbee/babyOne_r5yrzu.jpg",
        name: "The Bonder",
        age: "0-12 Weeks",
        slug: "0-12-months-the-bonder",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072908/Songbee/babyTwo_wwwfns.jpg",
        name: "The Feeler",
        age: "3-4 months",
        slug: "0-12-months-the-feeler",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072568/Songbee/babyThree_vboal1.jpg",
        name: "The Detector",
        age: "5-6 months",
        slug: "0-12-months-the-detector",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },

      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072556/Songbee/babyFour_ofxfso.jpg",
        name: "The Experimenter",
        age: "7-8 months",
        slug: "0-12-months-the-experimenter",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072542/Songbee/babyFive_gdsvsb.jpg",
        name: "The Investigator",
        age: "9-10 months",
        slug: "0-12-months-the-investigator",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714072564/Songbee/babySix_tknwqu.jpg",
        name: "The Discoverer",
        age: "11-12 months",
        slug: "0-12-months-the-discoverer",
        delivery: "Delivers | every 2 months",
        pricing: "$80/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
    ],
  },

  {
    id: 1,
    name: "1 year",
    description: "Build new skills and play to learn.",
    delivery: "Delivers | every 2 months",
    pricing: "$120/Pack",
    gridItems: 2,
    scrollId: "1_year",
    items: [
      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073363/Songbee/babyOne_q445gx.jpg",
        name: "The Talker",
        age: "13-14 months",
        slug: "1-year-the-talker",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073386/Songbee/babyTwo_gcggyn.jpg",
        name: "The Explorer",
        age: "15-16 months",
        slug: "1-year-the-explorer",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073380/Songbee/babyThree_v2wsiv.jpg",
        name: "The Pathfinder",
        age: "17-18 months",
        slug: "1-year-the-pathfinder",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },

      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073358/Songbee/babyFour_ejxqbj.jpg",
        name: "The Looker",
        age: "19-20 months",
        slug: "1-year-the-looker",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
    ],
  },

  {
    id: 2,
    name: "2 years",
    description: "Stimulate the brain and start making connections.",
    delivery: "Delivers | every 2 months",
    pricing: "$120/Pack",
    gridItems: 2,
    scrollId: "2_year",
    items: [
      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073509/Songbee/babyOne_qtdodv.jpg",
        name: "The Experimenter",
        age: "25-26 months",
        slug: "2-years-the-experimenter",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073528/Songbee/babyTwo_op35fc.jpg",
        name: "The Story Teller",
        age: "27-28 months",
        slug: "2-years-the-story-teller",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073517/Songbee/babyThree_b1rm5j.jpg",
        name: "The Creator",
        age: "29-30 months",
        slug: "2-years-the-creator",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },

      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073504/Songbee/babyFour_zhzybi.jpg",
        name: "The Adventurer",
        age: "31-32 months",
        slug: "2-years-the-adventurer",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "3 year",
    description: "Stimulate the brain and start making connections.",
    delivery: "Delivers | every 2 months",
    pricing: "$120/Pack",
    gridItems: 2,
    scrollId: "3_year",

    items: [
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073639/Songbee/babyOne_qbm7zu.jpg",
        name: "The Problem Solver",
        age: "37, 38, 39 months",
        slug: "3-year-the-problem-solver",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },

      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073662/Songbee/babyTwo_no332w.jpg",
        name: "The Tinkerer",
        age: "40, 41, 42 months",
        slug: "3-year-the-tinkerer",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073657/Songbee/babyThree_hhyawv.jpg",
        name: "The Bonder-1",
        age: "43, 44, 45 months",
        slug: "3-year-the-bonder-1",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073635/Songbee/babyFour_zrp2tt.jpg",
        name: "The Bonder-2",
        age: "46, 47, 48 months",
        slug: "3-year-the-bonder-2",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
    ],
  },

  {
    id: 4,
    name: "4 years",
    description: "Stimulate the brain and start making connections.",
    delivery: "Delivers | every 2 months",
    pricing: "$120/Pack",
    gridItems: 2,
    scrollId: "4_year",
    items: [
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073743/Songbee/babyOne_gwodu8.jpg",
        name: "The Bonder-1",
        age: "49, 50, 51, months",
        slug: "4-years-the-bonder-1",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },

      {
        id: 0,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073753/Songbee/babyTwo_zrnspn.jpg",
        name: "The Bonder-2",
        age: "52, 53, 54 months",
        slug: "4-years-the-bonder-2",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 1,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073747/Songbee/babyThree_xxputr.jpg",
        name: "The Bonder-3",
        age: "55, 56, 57 months",
        slug: "4-years-the-bonder-3",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
      {
        id: 2,
        imageUrl: "https://res.cloudinary.com/dke4ukd0z/image/upload/v1714073738/Songbee/babyFour_xlknjs.jpg",
        name: "The Bonder-4",
        age: "58, 59, 60 months",
        slug: "4-years-the-bonder-4",
        delivery: "Delivers | every 2 months",
        pricing: "$120/Pack",
        about:
          "With this learning pack, your baby will begin to adjust to sound and light. We start to stimulate the brain and start building neural connections with our thoughtfully developed music-based learning pack.",
        included: [
          "Lullabies(6)",
          "Hands and Toes Awareness Song",
          "Animal Sounds Song",
          "Color Song",
          "Play Guide",
        ],
      },
    ],
  },
];
